spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webchat?characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.xa.DruidXADataSource

mybatis:
  type-aliases-package: com.centling.chat.domain
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30